#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.


#####################################################################
# YOU SHOULD PUT THIS FILE IN /etc/grub.d/			    #
# IT WILL PROVIDE RESTART AND SHUTDOWN OPTIONS IN THE GRUB MENU	    #
#####################################################################


menuentry "Reboot" --class restart {
	reboot
}

menuentry "Shutdown" --class shutdown {
	halt
}
